name: Release

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  build-native:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            lib-path: libcurve25519.so
          - os: macos-latest
            lib-path: libcurve25519.dylib
          - os: windows-latest
            lib-path: Debug/curve25519.dll
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build native
        run: |
          mkdir jni/build
          cd jni/build
          cmake -DCMAKE_BUILD_TYPE=Release ..
          cmake --build .
      - name: Upload result
        uses: actions/upload-artifact@v1
        with:
          name: native
          path: jni/build/${{ matrix.lib-path }}

  release:
    runs-on: ubuntu-latest
    needs: build-native
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download native libs
        uses: actions/download-artifact@v1
        with:
          name: native
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Prepare to build
        run: |
          echo '${{ secrets.GPG_KEY_CONTENTS }}' | base64 -d > publish_key.gpg
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.SECRET_PASSPHRASE }}" --output secret.gpg publish_key.gpg
          mkdir -p java/src/main/resources/
          cp -r native java/src/main/resources/
      - name: Stage
        run:
          ./gradlew uploadArchives \
          -PsonatypeRepo=${{ secrets.SONATYPE_REPO }} \
          -PwhisperSonatypeUsername=${{ secrets.SONATYPE_USERNAME }} \
          -PwhisperSonatypePassword=${{ secrets.SONATYPE_PASSWORD }} \
          -Psigning.secretKeyRingFile=../secret.gpg \
          -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }} \
          -Psigning.password=${{ secrets.SIGNING_PASSWORD }}
      - name: Release
        run:
          ./gradlew closeAndReleaseRepository \
          -PsonatypeRepo= \
          -PwhisperSonatypeUsername=${{ secrets.SONATYPE_USERNAME }} \
          -PwhisperSonatypePassword=${{ secrets.SONATYPE_PASSWORD }} \
          -Psigning.secretKeyRingFile= \
          -Psigning.keyId= \
          -Psigning.password=
      - uses: actions/upload-artifact@v2
        with:
          name: released
          path: java/build/libs
